[tool.poetry]
name = "mwmbl"
version = "0.1.0"
description = ""
authors = ["Daoud Clarke <daoud.clarke@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^1.3.5"
scipy = "^1.8.0"
scikit-learn = "^1.0.2"
zstandard = "^0.16.0"
mmh3 = "^3.0.0"
uvicorn = "^0.16.0"
pyyaml = "==6.0"
boto3 = "1.35.99"
requests = "^2.27.1"
psycopg2-binary = "^2.9.3"
pytest = "^7.2.1"
pytest-mock = "^3.10.0"
lmdb-dict-full = "^1.0.2"

# Optional dependencies do not get installed by default. Look under tool.poetry.extras section
# to see which extras to use.
ujson = {version= "==4.3.0", optional = true}
warcio = {version= "==1.7.4", optional = true}
idna = {version= "==3.3", optional = true}
beautifulsoup4 = {version= "==4.10.0", optional = true}
langdetect = {version= "==1.0.9", optional = true}
pyarrow = {version= "==6.0.0", optional = true}
pyspark = {version= "==3.2.0", optional = true}
Levenshtein = {version= "==0.16.0", optional = true}
django = "^4.2.4"
django-ninja = "==1.4.0"
requests-cache = "^1.1.0"
redis = {extras = ["hiredis"], version = "^5.0.1"}
django-allauth = "^0.57.0"
dj-database-url = "^2.1.0"
django-htmx = "^1.17.0"
django-vite = "^2.1.3"
pybloomfiltermmap3 = "^0.6.0"
loguru = "^0.7.3"
lxml-html-clean = "^0.1.0"
lxml = "^5.2.0"
numpy = "1.23.2"
objgraph = "^3.6.1"
psutil = "^6.0.0"
xgboost = "^2.1.0"
pydistinct = "^0.6.4"
django-ninja-jwt = "^5.3.3"
sentry-sdk = "^2.13.0"

[tool.poetry.extras]
indexer = [
    "ujson",
    "warcio",
    "idna",
    "beautifulsoup4",
    "langdetect",
    "pyarrow",
    "pyspark",
    "Levenshtein",
]

[tool.poetry.dev-dependencies]
# botocore = "^1.23.20"
# boto3 = "^1.20.20"
# ujson = "^4.3.0"
# warcio = "^1.7.4"
# idna = "^3.3"
# beautifulsoup4 = "^4.10.0"
# lxml = "^4.6.4"
# jusText = "^3.0.0"
# pyspark = "^3.2.0"
# langdetect = "^1.0.9"
# spacy = "^3.2.1"
# Levenshtein = "^0.16.0"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mwmbl-tinysearchengine = "mwmbl.main:run"
mwmbl-crawl = "mwmbl.crawl:run"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
