# Generated by Django 4.2.11 on 2024-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mwmbl', '0005_oldindex'), ('mwmbl', '0006_remove_oldindex_index_total_pages_and_more'), ('mwmbl', '0007_alter_oldindex_last_copied_time_and_more')]

    dependencies = [
        ('mwmbl', '0004_curation_original_index_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldIndex',
            fields=[
                ('index_path', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('last_copied_time', models.DateTimeField(blank=True, null=True)),
                ('last_page_copied', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
