# Generated by Django 4.2.11 on 2024-04-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0005_oldindex_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('flag', models.CharField(choices=[('RELEVANCE', 'The curation is unlikely to be useful to a large number of users'), ('LANGUAGE', 'The curation is for a query in an unsupported language'), ('PROMOTION', 'The curation promotes a specific website or product'), ('OFFENSIVE', 'The curation contains offensive content'), ('OTHER', 'Other')], max_length=20)),
                ('reason', models.CharField(max_length=300)),
                ('curation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mwmbl.curation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
