# Generated by Django 4.2.11 on 2024-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0006_remove_oldindex_index_total_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldindex',
            name='last_copied_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldindex',
            name='last_page_copied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
