# Generated by Django 4.2.19 on 2025-06-08 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0010_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsubmission',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='domainsubmission',
            index=models.Index(fields=['submitted_on'], name='mwmbl_domai_submitt_cb7865_idx'),
        ),
    ]
