# Generated by Django 4.2.23 on 2025-07-19 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0011_alter_domainsubmission_submitted_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasmEvaluationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasm_file', models.BinaryField()),
                ('status', models.CharField(choices=[('PENDING', 'The evaluation job is pending'), ('VALIDATED', 'The WASM file has been validated'), ('RUNNING', 'The evaluation is currently running'), ('COMPLETED', 'The evaluation has completed successfully'), ('FAILED', 'The evaluation has failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
