# Generated by Django 4.2.23 on 2025-07-20 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0012_wasmevaluationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('query', models.CharField(max_length=300)),
                ('vote_type', models.CharField(choices=[('UPVOTE', 'User upvoted this result'), ('DOWNVOTE', 'User downvoted this result')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['url', 'query'], name='mwmbl_search_url_b8e7b8_idx'), models.Index(fields=['timestamp'], name='mwmbl_search_timesta_b8e7b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='searchresultvote',
            constraint=models.UniqueConstraint(fields=('user', 'url', 'query'), name='mwmbl_searchresultvote_user_url_query_unique'),
        ),
    ]
