# Generated by Django 5.2.13 on 2026-05-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0022_add_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilling',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
