# Generated by Django 5.2.13 on 2026-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0023_userbilling_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSearchImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512)),
                ('candidates', models.JSONField(default=list)),
                ('selected', models.JSONField(default=list)),
                ('features', models.JSONField(default=dict)),
                ('rewards', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='mwmbl_super_timesta_bbb2f8_idx')],
            },
        ),
    ]
