# Generated by Django 5.2.13 on 2026-06-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0024_supersearchimpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSearchBanditState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=128, unique=True)),
                ('dim', models.IntegerField()),
                ('a', models.BinaryField()),
                ('b', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
