# Generated by Django 5.2.13 on 2026-07-05 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0027_sourceprovenance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourceprovenance",
            name="query",
        ),
        migrations.RemoveField(
            model_name="supersearchimpression",
            name="query",
        ),
    ]
