# Generated by Django 5.2.13 on 2026-07-07 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0028_remove_sourceprovenance_query_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperSearchBanditState",
        ),
    ]
