# Generated by Django 5.2.13 on 2026-09-17 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0037_repair_domain_submission_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hostname", models.CharField(max_length=255)),
                ("friendly_name", models.CharField(blank=True, default="", max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="devices", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "hostname"], name="mwmbl_devic_user_id_6458c1_idx")],
                "unique_together": {("user", "hostname")},
            },
        ),
    ]
