# Generated by Django 5.2.13 on 2026-09-17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0038_apikey_last_used_device"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE batches ADD COLUMN device_name VARCHAR;
            """,
            """
            ALTER TABLE batches DROP COLUMN device_name;
            """,
        ),
    ]
