# Generated by Django 5.2.13 on 2026-09-24 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0038_apikey_last_used_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("num_results", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
                "indexes": [
                    models.Index(fields=["user", "date"], name="mwmbl_userst_user_id_abc123_idx"),
                ],
            },
        ),
    ]
