# Generated by Django 5.2.13 on 2026-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0039_userstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]