# Generated by Django 5.2.13 on 2026-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0039_userstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCrawlerStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("users_crawled", models.IntegerField(default=0)),
                ("results_indexed", models.IntegerField(default=0)),
                ("dataset_queries", models.IntegerField(default=0)),
                ("dataset_results", models.IntegerField(default=0)),
                ("blacklisted_results_removed", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyDomainResultCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("domain", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyIndexStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("urls_in_index", models.IntegerField(default=0)),
                ("domains_in_index", models.IntegerField(default=0)),
                ("results_in_index", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyTrafficStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("endpoint", models.CharField(max_length=50)),
                ("headers", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=10)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name="userstats",
            new_name="mwmbl_users_user_id_4fa2b9_idx",
            old_name="mwmbl_userst_user_id_abc123_idx",
        ),
        migrations.AddIndex(
            model_name="dailycrawlerstats",
            index=models.Index(fields=["-date"], name="mwmbl_daily_date_6c53ad_idx"),
        ),
        migrations.AddIndex(
            model_name="dailydomainresultcount",
            index=models.Index(fields=["-date"], name="mwmbl_daily_date_55d140_idx"),
        ),
        migrations.AddIndex(
            model_name="dailydomainresultcount",
            index=models.Index(fields=["domain", "-date"], name="mwmbl_daily_domain_aec678_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailydomainresultcount",
            unique_together={("date", "domain")},
        ),
        migrations.AddIndex(
            model_name="dailyindexstats",
            index=models.Index(fields=["-date"], name="mwmbl_daily_date_35cca0_idx"),
        ),
        migrations.AddIndex(
            model_name="dailytrafficstats",
            index=models.Index(fields=["-date"], name="mwmbl_daily_date_ac8d0e_idx"),
        ),
        migrations.AddIndex(
            model_name="dailytrafficstats",
            index=models.Index(fields=["date", "endpoint"], name="mwmbl_daily_date_b50373_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailytrafficstats",
            unique_together={("date", "endpoint", "headers", "status")},
        ),
    ]
