# Generated by Django 5.2.13 on 2026-10-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwmbl', '0040_dailycrawlerstats_dailydomainresultcount_and_more'),
        ('mwmbl', '0040_membership'),
    ]

    operations = [
    ]
