# Generated by Django 5.2.13 on 2026-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0040_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagebucket",
            name="combined_search_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usagebucket",
            name="reported_combined_search",
            field=models.IntegerField(default=0),
        ),
    ]
