# Generated by Django 5.2.13 on 2026-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0041_usagebucket_combined_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="mwmbluser",
            name="seed_search_pages_indexed",
            field=models.IntegerField(default=0),
        ),
    ]
