# Generated by Django 5.2.13 on 2026-10-02 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0040_membership"),
        ("mwmbl", "0041_dailycrawlerstats_dailydomainresultcount_and_more"),
    ]

    operations = []
