# Generated by Django 5.2.13 on 2026-10-10 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mwmbl", "0042_mwmbluser_seed_search_pages_indexed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=300, unique=True)),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("staan_results", models.IntegerField(default=0)),
                ("new_page_score", models.FloatField(default=0.0)),
                ("score", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="SeedDomainCrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crawled_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("pages_indexed", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="seeddomain",
            name="discovered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discovered_seed_domains",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seeddomaincrawl",
            name="seed_domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crawls",
                to="mwmbl.seeddomain",
            ),
        ),
        migrations.AddIndex(
            model_name="seeddomain",
            index=models.Index(fields=["-score"], name="mwmbl_seedd_score_503db3_idx"),
        ),
        migrations.AddIndex(
            model_name="seeddomaincrawl",
            index=models.Index(
                fields=["seed_domain", "-crawled_at"],
                name="mwmbl_seedd_seed_do_33878e_idx",
            ),
        ),
    ]
